import { Plan, PlanId } from '../../domain/types/auth';

export const PLANS_SEED: Plan[] = [
  {
    id: 'free_trial',
    name: 'Plano Gratuito / Trial',
    badge: '10 Dias Grátis',
    description: 'Ideal para conhecer todas as funcionalidades do Ateliê Sagrado ERP sem compromisso.',
    priceMonthly: 0,
    priceAnnual: 0,
    trialDays: 10,
    popular: false,
    limits: {
      maxUsers: 1,
      maxProducts: 15,
      maxOrdersPerMonth: 20,
      maxQuotesPerMonth: 30,
      maxStorageMb: 100,
    },
    features: [
      'Acesso completo por 10 dias',
      'Até 15 produtos com precificação',
      '20 pedidos de venda/mês',
      '30 orçamentos/mês',
      '1 operador de sistema',
      'Emissão de recibos e PDFs',
      'Suporte via e-mail'
    ],
    permissions: [
      'dashboard:read',
      'inventory:read',
      'inventory:write',
      'products:read',
      'products:write',
      'pricing:read',
      'clients:read',
      'clients:write',
      'quotes:read',
      'quotes:write',
      'orders:read',
      'orders:write',
      'production:read',
      'production:write',
      'financial:read'
    ],
    creditsMonthly: 50,
  },
  {
    id: 'basic',
    name: 'Plano Básico',
    badge: 'Para Iniciantes',
    description: 'Perfeito para artesãos e pequenos ateliês em fase de estruturação das vendas.',
    priceMonthly: 49,
    priceAnnual: 39,
    trialDays: 0,
    popular: false,
    limits: {
      maxUsers: 3,
      maxProducts: 50,
      maxOrdersPerMonth: 100,
      maxQuotesPerMonth: 150,
      maxStorageMb: 500,
    },
    features: [
      'Até 3 operadores cadastrados',
      'Até 50 produtos no catálogo',
      '100 pedidos por mês',
      '150 orçamentos por mês',
      '500 MB de armazenamento de fotos',
      'Relatórios financeiros essenciais',
      'Suporte por e-mail e WhatsApp'
    ],
    permissions: [
      'dashboard:read',
      'inventory:read',
      'inventory:write',
      'purchases:read',
      'purchases:write',
      'products:read',
      'products:write',
      'pricing:read',
      'pricing:write',
      'clients:read',
      'clients:write',
      'quotes:read',
      'quotes:write',
      'orders:read',
      'orders:write',
      'production:read',
      'production:write',
      'financial:read',
      'financial:write'
    ],
    creditsMonthly: 200,
  },
  {
    id: 'professional',
    name: 'Plano Profissional',
    badge: 'Mais Popular',
    description: 'A solução completa para ateliês consolidados com equipe e alto volume de produção.',
    priceMonthly: 119,
    priceAnnual: 99,
    trialDays: 0,
    popular: true,
    limits: {
      maxUsers: 10,
      maxProducts: 9999, // unlimited
      maxOrdersPerMonth: 500,
      maxQuotesPerMonth: 9999,
      maxStorageMb: 2048, // 2GB
    },
    features: [
      'Até 10 operadores e artesãos',
      'Catálogo de produtos ILIMITADO',
      'Até 500 pedidos por mês',
      'Orçamentos ILIMITADOS',
      '2 GB de armazenamento de imagens',
      'DRE e conciliação financeira avançada',
      'Motor de precificação avançado',
      'Atendimento prioritário'
    ],
    permissions: [
      'dashboard:read',
      'inventory:read',
      'inventory:write',
      'purchases:read',
      'purchases:write',
      'products:read',
      'products:write',
      'pricing:read',
      'pricing:write',
      'clients:read',
      'clients:write',
      'quotes:read',
      'quotes:write',
      'orders:read',
      'orders:write',
      'production:read',
      'production:write',
      'financial:read',
      'financial:write',
      'users:manage',
      'audit:read'
    ],
    creditsMonthly: 1000,
  },
  {
    id: 'enterprise',
    name: 'Plano Enterprise',
    badge: 'Sem Limites',
    description: 'Para redes de produção, franquias e grandes operações com necessidades sob medida.',
    priceMonthly: 299,
    priceAnnual: 249,
    trialDays: 0,
    popular: false,
    limits: {
      maxUsers: 999, // unlimited
      maxProducts: 9999,
      maxOrdersPerMonth: 9999,
      maxQuotesPerMonth: 9999,
      maxStorageMb: 10240, // 10GB
    },
    features: [
      'Usuários e artesãos ILIMITADOS',
      'Pedidos e orçamentos ILIMITADOS',
      '10 GB de armazenamento em nuvem',
      'Personalização de relatórios e marca',
      'Gerente de contas dedicado 24/7',
      'Logs detalhados de auditoria e segurança',
      'Suporte a múltiplas filiais'
    ],
    permissions: [
      'dashboard:read',
      'inventory:read',
      'inventory:write',
      'purchases:read',
      'purchases:write',
      'products:read',
      'products:write',
      'pricing:read',
      'pricing:write',
      'clients:read',
      'clients:write',
      'quotes:read',
      'quotes:write',
      'orders:read',
      'orders:write',
      'production:read',
      'production:write',
      'financial:read',
      'financial:write',
      'users:manage',
      'settings:manage',
      'subscription:manage',
      'audit:read'
    ],
    creditsMonthly: 5000,
  }
];
